---

- name: Install LibTIFF dependencies
  apt:
    name: "{{ item }}"
  become: yes
  become_user: root
  with_items:
    - git
    - build-essential

- name: Download LibTIFF
  git:
    repo: "https://github.com/vadz/libtiff.git"
    dest: "{{ vips_libtiff_path }}"
    version: "{{ vips_libtiff_version }}"
    update: no
    force: yes

- name: Build LibTIFF
  command: "{{ item }}"
  args:
    chdir: "{{ vips_libtiff_path }}"
  with_items:
    - "./configure"
    - "make -j{{ build_parallelism }}"

- name: Install LibTIFF
  command: "{{ item }}"
  args:
    chdir: "{{ vips_libtiff_path }}"
  become: yes
  become_user: root
  with_items:
    - "make install"
    - "ldconfig"
