---
# tasks file for vips

- name: Check for installed OpenJPEG
  find:
    patterns: "libopenjpeg.so"
    paths: "/usr/local/lib"
  register: vips_openjpeg_find_installed

- include: tasks/openjpeg.yml
  when: "vips_openjpeg_find_installed.matched == 0"


- name: Check for installed LibTIFF
  find:
    patterns: "libtiff.so"
    paths: "/usr/local/lib"
  register: vips_libtiff_find_installed

- include: tasks/libtiff.yml
  when: "vips_libtiff_find_installed.matched == 0"


- name: Check for installed OpenSlide
  find:
    patterns: "libopenslide.so"
    paths: "/usr/local/lib"
  register: vips_openslide_find_installed

- include: tasks/openslide.yml
  when: "vips_openslide_find_installed.matched == 0"


- name: Check for installed VIPS
  find:
    patterns: "vips"
    paths: "/usr/local/bin"
  register: vips_find_installed

- include: tasks/vips.yml
  when: "vips_find_installed.matched == 0"
